### ISSUE TITLE
OpenAL-1.6.0.1 does not compile

### ISSUE THREAD

**Issue by peti** [haskell-openal/ALUT#4]
Citing from http://hydra.cryp.to/build/659710/nixlog/1/raw:

    Preprocessing library OpenAL-1.6.0.1...

    src/Sound/OpenAL.hs:48:8:
        Could not find module ‘Graphics.Rendering.OpenGL.GL.ObjectName’
        Perhaps you meant
          Graphics.Rendering.OpenGL.GL.Selection (from OpenGL-2.12.0.0)
          Graphics.Rendering.OpenGL.GL.Bitmaps (from OpenGL-2.12.0.0)
          Graphics.Rendering.OpenGL.GL.Feedback (from OpenGL-2.12.0.0)
        Use -v to see a list of the files searched for.

    src/Sound/OpenAL.hs:49:8:
        Could not find module ‘Graphics.Rendering.OpenGL.GL.StateVar’
        Perhaps you meant
          Graphics.Rendering.OpenGL.GL.Shaders (from OpenGL-2.12.0.0)
          Graphics.Rendering.OpenGL.GL.Bitmaps (from OpenGL-2.12.0.0)
          Graphics.Rendering.OpenGL.GL.Hints (from OpenGL-2.12.0.0)
        Use -v to see a list of the files searched for.

**Comment by svenpanne** [comment]
Ooops, the OpenAL package was missing an upper bound on the OpenGL dependency. I added it, please do a ``cabal update``, retry and tell me if that worked.

**Comment by peti** [comment]
Well, the upper bound is not going to help us (the NixOS distribution) because we've already updated to OpenGL-2.12.0.0.

Anyway, it's good that the upper bound is now there for those installing with `cabal-install`.

**Comment by svenpanne** [comment]
OK... I just uploaded new versions of the OpenAL and ALUT packages to Hackage. It would be nice to know if that fixes things for you.

**Comment by peti** [comment]
Yes, the new version fixes the build error: http://hydra.cryp.to/eval/294660#tabs-now-succeed. Thank you for the quick update!
